included:
  - WKJavaScriptController
  - WKJavaScriptController-Demo

excluded:
  - Pods

variable_name:
  min_length:
    warning: 0
    error: 0

disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - todo
  - type_body_length
  - line_length
  - trailing_whitespace
  - cyclomatic_complexity
  - variable_name
